### ISSUE TITLE
Flag section

### ISSUE THREAD

**Issue by CePeU** [GamerFlix/foundryvtt-api-guide#12]
Thanks for your help on discord! Your site and the others you suggested allready have been tremendously helpfull for me and gave me much better insight! THANKS!

So as to the topic in the title:

A little section about flags and what they can be used for (storing data on macros or somewehere else) could be  helpfull.

Most of the times a macro programmer does not have its own "space". So knowing and beeing able to save things could be really helpfull.

**Comment by CePeU** [comment]
I agree with your general assesment. I think the best point is to clarify which have been the striking revelations (beeing a noob in this) for me or the things I think I understood (which migth still be wrong):
a) Flags are only called flags (and not a false/true information) but in essence as you point out are a property as any other with the exception that they are outside of a specific scope (like modules)
b) They can essentially hold any information and data structure
c) As mentioned they are "out of scope" so one ideally needs to make sure they do not collide with module data or anything else
d) They can be stored on any document (this was one of the most important things) thus one can store them on the macro itself

+Anything else which could make them tricky and I did not reallize yet ;)

So a general section with a concept description, what they are used for, how they work technically (see above) and as you mentioned convention of structure would be helpfull as it faciliates general understanding.

Thanks again for your help!!!

**Comment by GamerFlix** [comment]
@CePeU If you have the time I'd appreciate it if you would take a look at the commit seen above to determine whether the new section outlines the topic sufficiently

**Comment by GamerFlix** [comment]
Going to merge this now after peer review from others outside of Github

**Comment by CePeU** [comment]
Thank you looks also good to me. Sorry for the late reply but I was not really logged on for some time ... holiday season and end of year stuff.
