### ISSUE TITLE
Verify the section on synthetic Actors is corect for v11

### ISSUE THREAD

**Issue by GamerFlix** [GamerFlix/foundryvtt-api-guide#4]
To my understanding the way synthetic actors and how the delta between the synthetic actor and the source actor is handled was adusted in v11. As such the final section on synthetic tokens might need adjustment.

**Comment by krbz999** [comment]
![image](https://github.com/GamerFlix/foundryvtt-api-guide/assets/50169243/d5680e62-d11b-4762-b631-5f7d0074c0af)

TL;DR: Treat them as if they were (more) normal actors.

**Comment by GamerFlix** [comment]
Apart from entirely deleting the section, which would overall be less information IMO, that doesn't seem actionable.
